version: '3.0'

# list of services in the Docker
services:

  # detectron2 container configuration
  recipt_scan:
    container_name: recipt_scan
    # image:
    build: .
    stdin_open: true
    tty: true
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - .:/code
    ports:
      - '${FASTAPI_LOCAL_PORT}:${FASTAPI_DOCKER_PORT}'

    environment:
      # detectron2 env
      ENV: ${ENV}